### ISSUE TITLE
Error getting powermeter(s)_data

### ISSUE THREAD

**Issue by bstaeheli** [vchrisb/e3dc-rest#28]
At moment I'm not able to get the powermeter_data. It results in "Internal Server Error":

```
e3dc-rest            | [2022-03-12 12:56:26,715] ERROR in app: Exception on /api/powermeter_data [GET]
e3dc-rest            | Traceback (most recent call last):
e3dc-rest            |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
e3dc-rest            |     rv = self.dispatch_request()
e3dc-rest            |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
e3dc-rest            |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
e3dc-rest            |   File "/usr/local/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
e3dc-rest            |     resp = resource(*args, **kwargs)
e3dc-rest            |   File "/usr/local/lib/python3.9/site-packages/flask/views.py", line 84, in view
e3dc-rest            |     return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
e3dc-rest            |   File "/usr/local/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
e3dc-rest            |     resp = meth(*args, **kwargs)
e3dc-rest            |   File "/usr/local/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
e3dc-rest            |     return self.ensure_sync(f)(*args, **kwargs)
e3dc-rest            |   File "/app/api.py", line 93, in get
e3dc-rest            |     return e3dc.get_powermeter_data(keepAlive=True)
e3dc-rest            |   File "/usr/local/lib/python3.9/site-packages/e3dc/_e3dc.py", line 1739, in get_powermeter_data
e3dc-rest            |     activePhases = f"{activePhasesChar:03b}"
e3dc-rest            | TypeError: unsupported format string passed to NoneType.__format__
e3dc-rest            | 192.168.90.254 - admin [12/Mar/2022:12:56:26 +0100] "GET /api/powermeter_data HTTP/1.1" 500 37 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:98.0) Gecko/20100101 Firefox/98.0"
e3dc-rest            | [2022-03-12 12:56:44,083] ERROR in app: Exception on /api/powermeters_data [GET]
e3dc-rest            | Traceback (most recent call last):
e3dc-rest            |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
e3dc-rest            |     rv = self.dispatch_request()
e3dc-rest            |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
e3dc-rest            |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
e3dc-rest            |   File "/usr/local/lib/python3.9/site-packages/flask_restful/__init__.py", line 467, in wrapper
e3dc-rest            |     resp = resource(*args, **kwargs)
e3dc-rest            |   File "/usr/local/lib/python3.9/site-packages/flask/views.py", line 84, in view
e3dc-rest            |     return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
e3dc-rest            |   File "/usr/local/lib/python3.9/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
e3dc-rest            |     resp = meth(*args, **kwargs)
e3dc-rest            |   File "/usr/local/lib/python3.9/site-packages/flask_httpauth.py", line 172, in decorated
e3dc-rest            |     return self.ensure_sync(f)(*args, **kwargs)
e3dc-rest            |   File "/app/api.py", line 98, in get
e3dc-rest            |     return e3dc.get_powermeters_data(keepAlive=True)
e3dc-rest            |   File "/usr/local/lib/python3.9/site-packages/e3dc/_e3dc.py", line 1782, in get_powermeters_data
e3dc-rest            |     self.get_powermeter_data(
e3dc-rest            |   File "/usr/local/lib/python3.9/site-packages/e3dc/_e3dc.py", line 1739, in get_powermeter_data
e3dc-rest            |     activePhases = f"{activePhasesChar:03b}"
```

It runs in a docker container, built from the sources from the [current commit 86ed168](https://github.com/vchrisb/e3dc-rest/commit/86ed1685b7b38a5d436d7ca64dc816f10483e271) against an e3dc S10 Pro

**Comment by vchrisb** [comment]
Your system might not return a value for "active phases" and this case is currently not handled:
https://github.com/fsantini/python-e3dc/blob/master/e3dc/_e3dc.py#L1783

Can you please open an issue here https://github.com/fsantini/python-e3dc/issues with information of your system?
Other folks are using the underlying library with an E3DC S10 Pro, not sure what is different with your implementation.
