### ISSUE TITLE
struct.error: unpack requires a buffer of 2 bytes

### ISSUE THREAD

**Issue by venyosdh** [vchrisb/e3dc-rest#40]
Solved it, it's the RSCP password and local user password found under Personalization - RSCP password, maybe that can be noted in Readme, thank you :)

When I'm trying to execute python3 api.py, I get the following exception. E3DC_KEY is set to 'secretkey' and ADMIN_PASSWORD is set to 'admin', that is probably wrong? I don't know where to get the right values for that

`Traceback (most recent call last):
  File "/home/pi/E3DCAPI/.venv/lib/python3.9/site-packages/e3dc/_e3dc_rscp_local.py", line 83, in sendRequest
    receive = self._receive()
  File "/home/pi/E3DCAPI/.venv/lib/python3.9/site-packages/e3dc/_e3dc_rscp_local.py", line 61, in _receive
    decData = rscpDecode(self.encdec.decrypt(data))[0]
  File "/home/pi/E3DCAPI/.venv/lib/python3.9/site-packages/e3dc/_rscpLib.py", line 205, in rscpDecode
    magic = struct.unpack(magicCheckFmt, data[: struct.calcsize(magicCheckFmt)])[0]
struct.error: unpack requires a buffer of 2 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/E3DCAPI/.venv/lib/python3.9/site-packages/e3dc/_e3dc.py", line 500, in sendRequest
    self.rscp.connect()
  File "/home/pi/E3DCAPI/.venv/lib/python3.9/site-packages/e3dc/_e3dc_rscp_local.py", line 112, in connect
    self.sendRequest(
  File "/home/pi/E3DCAPI/.venv/lib/python3.9/site-packages/e3dc/_e3dc_rscp_local.py", line 86, in sendRequest
    raise CommunicationError
e3dc._e3dc_rscp_local.CommunicationError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/E3DCAPI/e3dc-rest/api/api.py", line 33, in <module>
    e3dc = E3DC(
  File "/home/pi/E3DCAPI/.venv/lib/python3.9/site-packages/e3dc/_e3dc.py", line 142, in __init__
    self.get_system_info_static(keepAlive=True)
  File "/home/pi/E3DCAPI/.venv/lib/python3.9/site-packages/e3dc/_e3dc.py", line 890, in get_system_info_static
    self.sendRequestTag("EMS_REQ_DERATE_AT_PERCENT_VALUE", keepAlive=True) * 100
  File "/home/pi/E3DCAPI/.venv/lib/python3.9/site-packages/e3dc/_e3dc.py", line 534, in sendRequestTag
    return self.sendRequest(
  File "/home/pi/E3DCAPI/.venv/lib/python3.9/site-packages/e3dc/_e3dc.py", line 510, in sendRequest
    raise SendError("Max retries reached")
e3dc._e3dc.SendError: Max retries reached`

Sorry if I did something about this wrong. New to git + Linux

**Comment by ubarni** [comment]
You find the E3DC_KEY in your E2DC Portal in "Benutzerprofil".
You may have to create the CloudKey first?
ADMIN_PASSWORD is the RSCP password set in the E3DC Panel Display.
You must activate RSCP first.

BUT: I set these parameter already correct and got the same error!
I used a Docker Debian Linux on my Synology DS218+ NAS.

**Comment by ubarni** [comment]
Looks i was wrong with the ADMIN_PASSWORD?
Seems not to be the E3DC RSCP Password but the ADMIN Password for the Rest-API?

**Comment by vchrisb** [comment]
yes, `ADMIN_PASSWORD` is for the API and defaults to `admin`

The other parameter are for E3DC:

E3DC_KEY (aka rscp password): The RSCP Password (encryption key), as set on the device under Main Page -> Personalize -> User profile -> RSCP password

The underlying package used is https://github.com/fsantini/python-e3dc

**Comment by ubarni** [comment]
**SOLVED!**
I checked Python-REST and found this:
`The RSCP Password (encryption key), as set on the device under Main Page -> Personalize -> User profile -> RSCP password`
So E3DC_KEY is the RSCP Password set on the E3DC Display (Hauptmenü > Personalisieren > Benutzerprofil)
ADMIN_PASSWORD i set to 'admin' meanwhile and now the service starts without errors

**Comment by ubarni** [comment]
Maybe it would help to add this to the README that:

- E3DC_KEY is the RSCP password (can be mixed up with the E3DC Cloud Key!)
- ADMIN_PASSWORD is 'admin' default (and how it can be changed?) I thought this is the RSCP password...

**Comment by ubarni** [comment]
THX @vchrisb to clarify this in the README 👍🏼

**Comment by vchrisb** [comment]
I also enhanced the upstream package https://github.com/fsantini/python-e3dc to raise a 'RSCPKeyError` if the encryption key is wrong.
There is also an update docker image.
